# Generated by Django 4.2 on 2025-11-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A short title for this rule (e.g., 'Exclude popular options').", max_length=255, unique=True)),
                ('text', models.TextField(help_text='The actual text of the rule to be inserted into the prompt.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules (Non-Negotiables)',
            },
        ),
        migrations.CreateModel(
            name='PromptStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short title for this reasoning step.', max_length=255, unique=True)),
                ('text', models.TextField(help_text='The actual reasoning step to be inserted into the prompt.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reasoning Step',
                'verbose_name_plural': 'Reasoning Steps (Internal Logic)',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for this template (e.g., 'YouTube Script Breakdown').", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal notes about when to use this template.')),
                ('role_text', models.TextField(help_text="The 'You are...' definition for the # ROLE section.")),
                ('task_text', models.TextField(help_text='The core objective for the ## TASK section.')),
                ('context_text', models.TextField(blank=True, help_text='Any grounding information for the ## CONTEXT section (optional).', null=True)),
                ('stop_conditions', models.TextField(blank=True, help_text="The criteria for the ## STOP CONDITIONS section (e.g., 'Task is complete when...').", null=True)),
                ('output_format', models.TextField(blank=True, help_text="The required structure for the ## OUTPUT FORMAT section (e.g., 'Return results as a JSON object...').", null=True)),
                ('reasoning_steps', models.ManyToManyField(blank=True, help_text='Select internal reasoning/validation steps for the ## REASONING section.', related_name='templates', to='prompt_house.promptstep')),
                ('rules', models.ManyToManyField(blank=True, help_text='Select specific rules for the # RULES section.', related_name='templates', to='prompt_house.promptrule')),
            ],
            options={
                'verbose_name': 'Prompt Template',
                'verbose_name_plural': 'Prompt Templates (The Prompt House)',
            },
        ),
    ]
