# Generated by Django 4.2 on 2025-11-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPromptField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_key', models.CharField(help_text="The label for the field (e.g., 'Target Platform').", max_length=100)),
                ('field_value', models.TextField(help_text="The value for this field (e.g., 'Short video format').")),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='The order in which to display this field.')),
                ('template', models.ForeignKey(help_text='The prompt template this custom field belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='prompt_house.prompttemplate')),
            ],
            options={
                'verbose_name': 'Dynamic Parameter',
                'verbose_name_plural': 'Dynamic Parameters (Fixed Visual Parameters)',
                'ordering': ['order', 'label_key'],
            },
        ),
    ]
