# Generated by Django 4.2 on 2025-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_recorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('content_id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Content ID')),
                ('idea_name', models.CharField(max_length=255, unique=True, verbose_name='Idea Name/Title')),
                ('raw_content', models.TextField(verbose_name='Original Content')),
                ('source_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Content_recorderItem',
        ),
    ]
