# Generated by Django 4.2 on 2025-11-23 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_recorder', '0002_contentidea_delete_content_recorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentidea',
            name='source_file_name',
        ),
        migrations.AddField(
            model_name='contentidea',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea_images/'),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='status',
            field=models.CharField(choices=[('Draft', 'Idea Stage (Drafting)'), ('Future', 'Future Use (Backlog)'), ('Duplicate', 'Duplicate Idea'), ('Script', 'Moved to Script Writer'), ('Planner', 'In Planner (Scheduled)'), ('Archive', 'Archived/Completed')], default='Draft', max_length=10, verbose_name='Idea Status'),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='content_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='idea_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='raw_content',
            field=models.TextField(verbose_name='Primary Content/Notes'),
        ),
        migrations.CreateModel(
            name='IdeaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='content_recorder.contentidea')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('Text', 'Pasted Text/Notes'), ('URL', 'Web Link/Article'), ('File', 'Document File (.pdf, .doc, .txt)'), ('Image', 'Attached Image')], max_length=5)),
                ('source_data', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='content_recorder.contentidea')),
            ],
        ),
    ]
