# Generated by Django 4.2 on 2025-11-23 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_recorder', '0003_remove_contentidea_source_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentidea',
            name='content_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='idea_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Idea Name/Title'),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea_images/', verbose_name='Primary Image/Thumbnail'),
        ),
        migrations.AlterField(
            model_name='idealog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
