# Generated by Django 4.2 on 2025-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_recorder', '0004_alter_contentidea_content_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentidea',
            options={'verbose_name': 'Content Idea', 'verbose_name_plural': 'Content Ideas'},
        ),
        migrations.RemoveField(
            model_name='idealog',
            name='details',
        ),
        migrations.AddField(
            model_name='contentidea',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='content_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='idea_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Idea Title'),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='raw_content',
            field=models.TextField(verbose_name='Raw Input Content'),
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft (New Idea)'), ('Research', 'Research/Data Gathering'), ('Script', 'Script Ready'), ('Production', 'In Production'), ('Published', 'Published'), ('Archived', 'Archived'), ('Duplicate', 'Duplicate/Rejected')], default='Draft', max_length=50, verbose_name='Workflow Status'),
        ),
        migrations.AlterField(
            model_name='contentsource',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentsource',
            name='source_type',
            field=models.CharField(choices=[('Text', 'Pasted Text'), ('File', 'File Upload'), ('URL', 'Web Link/URL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='idealog',
            name='action',
            field=models.TextField(),
        ),
    ]
