# Generated by Django 4.2 on 2025-11-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_recorder', '0005_alter_contentidea_options_remove_idealog_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown_data', models.JSONField()),
                ('prompt_used', models.CharField(max_length=50, verbose_name='LLM Prompt Version')),
                ('target_platform', models.CharField(max_length=50)),
                ('global_mood', models.CharField(max_length=50)),
                ('target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='content_recorder.contentidea')),
            ],
        ),
    ]
