# Generated by Django 4.2 on 2025-11-26 01:53

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_recorder', '0006_scriptbreakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_index', models.IntegerField(help_text='Index or ID of the scene in the ScriptBreakdown.')),
                ('image_file', models.ImageField(help_text='The generated image file.', upload_to='storyboards/%Y/%m/')),
                ('full_prompt', models.TextField(help_text='The exact prompt used to generate this image.')),
                ('camera_angle', models.CharField(help_text='e.g., Wide shot, Close up.', max_length=100)),
                ('style_prompt', models.CharField(help_text='e.g., Film noir aesthetic.', max_length=255)),
                ('negative_prompt', models.TextField(help_text='The negative prompt used.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Set to True for soft deletion.')),
                ('trash_file', models.FileField(blank=True, help_text='Storage location if image is soft-deleted.', null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/www/media/storyboard_trash'), upload_to='trash/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(help_text='The core idea this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='scene_images', to='content_recorder.contentidea')),
            ],
        ),
    ]
