# Generated by Django 4.2 on 2025-11-26 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_house', '0001_initial'),
        ('content_recorder', '0007_sceneimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentidea',
            name='prompt_template',
            field=models.ForeignKey(blank=True, help_text='The structured template to use for generating the Script Breakdown.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompt_house.prompttemplate'),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='title',
            field=models.CharField(default='Unknown Title', help_text='The primary name for the content.', max_length=255, verbose_name='Idea Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentidea',
            name='idea_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Idea Title (Secondary)'),
        ),
    ]
